---
language: node_js
node_js:
  - "8"

sudo: true
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - $HOME/.cache/yarn

env:
  global:
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Full Test Suite"
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test-node
        - yarn test
    # Officially we still support Node 6 until ECM 2.0, but unfortunately
    # many of our dependencies have dropped Node 6 in non-breaking releases,
    # which makes running the full suite hard. We run the browser test suite
    # with locked dependencies as a reasonable smoke test instead.
    - name: "Node 6 Tests"
      script:
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=babel-6
    - env: EMBER_TRY_SCENARIO=stage-2-decorators
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
